package com.example.herve.Study.greendao.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.herve.Study.bean.ExaminationPaperBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "EXAMINATION_PAPER_BEAN".
*/
public class ExaminationPaperBeanDao extends AbstractDao<ExaminationPaperBean, Long> {

    public static final String TABLENAME = "EXAMINATION_PAPER_BEAN";

    /**
     * Properties of entity ExaminationPaperBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property ExaminationPaperId = new Property(0, Long.class, "examinationPaperId", true, "_id");
        public final static Property Grade = new Property(1, String.class, "grade", false, "GRADE");
        public final static Property Author = new Property(2, String.class, "author", false, "AUTHOR");
        public final static Property PaperDifficulty = new Property(3, int.class, "paperDifficulty", false, "PAPER_DIFFICULTY");
        public final static Property PaperType = new Property(4, int.class, "paperType", false, "PAPER_TYPE");
    }

    private DaoSession daoSession;


    public ExaminationPaperBeanDao(DaoConfig config) {
        super(config);
    }
    
    public ExaminationPaperBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"EXAMINATION_PAPER_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: examinationPaperId
                "\"GRADE\" TEXT," + // 1: grade
                "\"AUTHOR\" TEXT," + // 2: author
                "\"PAPER_DIFFICULTY\" INTEGER NOT NULL ," + // 3: paperDifficulty
                "\"PAPER_TYPE\" INTEGER NOT NULL );"); // 4: paperType
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"EXAMINATION_PAPER_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ExaminationPaperBean entity) {
        stmt.clearBindings();
 
        Long examinationPaperId = entity.getExaminationPaperId();
        if (examinationPaperId != null) {
            stmt.bindLong(1, examinationPaperId);
        }
 
        String grade = entity.getGrade();
        if (grade != null) {
            stmt.bindString(2, grade);
        }
 
        String author = entity.getAuthor();
        if (author != null) {
            stmt.bindString(3, author);
        }
        stmt.bindLong(4, entity.getPaperDifficulty());
        stmt.bindLong(5, entity.getPaperType());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ExaminationPaperBean entity) {
        stmt.clearBindings();
 
        Long examinationPaperId = entity.getExaminationPaperId();
        if (examinationPaperId != null) {
            stmt.bindLong(1, examinationPaperId);
        }
 
        String grade = entity.getGrade();
        if (grade != null) {
            stmt.bindString(2, grade);
        }
 
        String author = entity.getAuthor();
        if (author != null) {
            stmt.bindString(3, author);
        }
        stmt.bindLong(4, entity.getPaperDifficulty());
        stmt.bindLong(5, entity.getPaperType());
    }

    @Override
    protected final void attachEntity(ExaminationPaperBean entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ExaminationPaperBean readEntity(Cursor cursor, int offset) {
        ExaminationPaperBean entity = new ExaminationPaperBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // examinationPaperId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // grade
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // author
            cursor.getInt(offset + 3), // paperDifficulty
            cursor.getInt(offset + 4) // paperType
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ExaminationPaperBean entity, int offset) {
        entity.setExaminationPaperId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setGrade(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setAuthor(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setPaperDifficulty(cursor.getInt(offset + 3));
        entity.setPaperType(cursor.getInt(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ExaminationPaperBean entity, long rowId) {
        entity.setExaminationPaperId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ExaminationPaperBean entity) {
        if(entity != null) {
            return entity.getExaminationPaperId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ExaminationPaperBean entity) {
        return entity.getExaminationPaperId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
